#!/usr/bin/env bash

# Install nginx if not already installed
sudo apt update
sudo apt install nginx -y

# Create a default index.html file
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html

# Create a new configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations can be added here if needed

}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo service nginx restart
